name: "MTProto Proxy"
description: "Use your homeassistant instance as a proxy for Telegram"
version: "0.0.1"
slug: "mtprotoproxy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: "ghcr.io/donetick/{arch}-hassio-addons"

ports:
  443/tcp: 444

options:
  users:
    - name: tg
      secret: "00000000000000000000000000000001"
  modes:
    classic: false
    secure: false
    tls: true
  tls_domain: "www.google.com"
  ad_tag: ""

schema:
  users:
    - name: "str"
      secret: "match(^[0-9]{32}$)"
  modes:
    classic: "bool"
    secure: "bool"
    tls: "bool"
  tls_domain: "str"
  ad_tag: "str?"